stages:

  get_data:
    cmd: python -m src.get_data
    deps:
    - src/get_data.py
    - config/get_data.yaml
    outs:
    - data/get_data.parquet

  features:
    cmd: python -m src.features
    deps:
    - src/features.py
    - config/features.yaml
    - data/get_data.parquet
    outs:
    - data/features.parquet

  target:
    cmd: python -m src.target
    deps:
    - src/target.py
    - config/target.yaml
    - data/get_data.parquet
    outs:
    - data/target.parquet