defaults:
  - model: random_forest

features:
  - sma_50
  - sma_100
  - sma_200

steps:
  selector:
    _target_: src.model.ColumnSelector
    columns: ${features}
  classifier: ${model}

input_path: ???
model_path: ???
metrics_path: ???



